# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainFrom.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 480)
        Form.setMinimumSize(QtCore.QSize(400, 480))
        Form.setMaximumSize(QtCore.QSize(400, 480))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(11, 19, 375, 448))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_16 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonOpenDevice = QtWidgets.QRadioButton(self.widget)
        self.radioButtonOpenDevice.setObjectName("radioButtonOpenDevice")
        self.horizontalLayout.addWidget(self.radioButtonOpenDevice)
        self.radioButtonInitCAN = QtWidgets.QRadioButton(self.widget)
        self.radioButtonInitCAN.setObjectName("radioButtonInitCAN")
        self.horizontalLayout.addWidget(self.radioButtonInitCAN)
        self.radioButtonStartCAN = QtWidgets.QRadioButton(self.widget)
        self.radioButtonStartCAN.setObjectName("radioButtonStartCAN")
        self.horizontalLayout.addWidget(self.radioButtonStartCAN)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textBrowserCountDown = QtWidgets.QTextBrowser(self.widget)
        self.textBrowserCountDown.setMidLineWidth(1)
        self.textBrowserCountDown.setObjectName("textBrowserCountDown")
        self.gridLayout_4.addWidget(self.textBrowserCountDown, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEditChangeTime = QtWidgets.QLineEdit(self.widget)
        self.lineEditChangeTime.setObjectName("lineEditChangeTime")
        self.gridLayout.addWidget(self.lineEditChangeTime, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.lineEditCycleNum = QtWidgets.QLineEdit(self.widget)
        self.lineEditCycleNum.setReadOnly(True)
        self.lineEditCycleNum.setObjectName("lineEditCycleNum")
        self.gridLayout.addWidget(self.lineEditCycleNum, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 2, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.widget)
        self.timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit.setTime(QtCore.QTime(20, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout.addWidget(self.timeEdit, 0, 1, 1, 2)
        self.timeEditTotolTime = QtWidgets.QTimeEdit(self.widget)
        self.timeEditTotolTime.setReadOnly(True)
        self.timeEditTotolTime.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEditTotolTime.setObjectName("timeEditTotolTime")
        self.gridLayout.addWidget(self.timeEditTotolTime, 1, 1, 1, 2)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.widget)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout.addWidget(self.timeEdit_2, 2, 1, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonStart = QtWidgets.QPushButton(self.widget)
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.horizontalLayout_2.addWidget(self.pushButtonStart)
        self.pushButtonPause = QtWidgets.QPushButton(self.widget)
        self.pushButtonPause.setObjectName("pushButtonPause")
        self.horizontalLayout_2.addWidget(self.pushButtonPause)
        self.pushButtonStop = QtWidgets.QPushButton(self.widget)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.horizontalLayout_2.addWidget(self.pushButtonStop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEditYunxing = QtWidgets.QLineEdit(self.widget)
        self.lineEditYunxing.setObjectName("lineEditYunxing")
        self.gridLayout_2.addWidget(self.lineEditYunxing, 0, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineEditWeizhi = QtWidgets.QLineEdit(self.widget)
        self.lineEditWeizhi.setObjectName("lineEditWeizhi")
        self.gridLayout_2.addWidget(self.lineEditWeizhi, 1, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.lineEditDianliu = QtWidgets.QLineEdit(self.widget)
        self.lineEditDianliu.setObjectName("lineEditDianliu")
        self.gridLayout_2.addWidget(self.lineEditDianliu, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "推杆电机控制程序"))
        self.label_16.setText(_translate("Form", "推杆电机循环控制软件"))
        self.radioButtonOpenDevice.setText(_translate("Form", "OpenDevice"))
        self.radioButtonInitCAN.setText(_translate("Form", "InitCAN"))
        self.radioButtonStartCAN.setText(_translate("Form", "StartCAN"))
        self.label_15.setText(_translate("Form", "动作倒计时"))
        self.label_12.setText(_translate("Form", "计划总时间"))
        self.label_4.setText(_translate("Form", "累计运行时间"))
        self.label_5.setText(_translate("Form", "剩余时间"))
        self.label.setText(_translate("Form", "当前循环次数"))
        self.label_3.setText(_translate("Form", "s"))
        self.label_2.setText(_translate("Form", "换相时间"))
        self.label_18.setText(_translate("Form", "次"))
        self.timeEdit.setDisplayFormat(_translate("Form", "H:mm"))
        self.pushButtonStart.setText(_translate("Form", "开始"))
        self.pushButtonPause.setText(_translate("Form", "暂停"))
        self.pushButtonStop.setText(_translate("Form", "停止"))
        self.label_6.setText(_translate("Form", "运行状态"))
        self.label_13.setText(_translate("Form", "位置状态"))
        self.label_14.setText(_translate("Form", "电流"))
        self.label_17.setText(_translate("Form", "A"))
        self.label_7.setText(_translate("Form", "故障列表"))
        self.label_8.setText(_translate("Form", "开路"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.label_9.setText(_translate("Form", "过流"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.label_10.setText(_translate("Form", "堵转"))
        self.pushButton_3.setText(_translate("Form", "PushButton"))
        self.label_11.setText(_translate("Form", "异常"))
        self.pushButton_4.setText(_translate("Form", "PushButton"))

